In [1]:
import polars as pl
import duckdb
from pathlib import Path

pl.Config.set_fmt_str_lengths(100)
data_path = Path("../data")

In [2]:
# Read available files
datasets = pl.read_csv(data_path / "Datasets 9424.csv")

# Read kg files
conn = duckdb.connect(data_path / "event_datasets.duckdb")
datasets_id = conn.query("FROM kg_datasets SELECT *").pl()
datasets_vars = conn.query("FROM kg_variables SELECT *").pl()

In [3]:
# Merge
df = (
    datasets
    .join(datasets_id, left_on="Bestandsnaam", right_on="alt_title", how="left")
)

In [4]:
# No matching to KG (11 real datasets that are not matched)
(
    df
    .filter(pl.col("is_frequency_dataset").is_null())
    ["Bestandsnaam"]
    .to_list()
)

['9424_LISS_background_survey_merged_for_importCBKV1',
 '9424_LISS_core_studies_long_updCBKV1.csv',
 '9424_LISS_core_studies_longCBKV1',
 '9424_ZYGV2_942420250724CBKV1',
 'EIGENDOMTAB',
 'EIGENDOMWOZBAGTAB',
 'EIGENDOMWOZTAB',
 'GBAPERSOONKTAB',
 'GBASCHEIDINGENMASSATAB',
 'KINDEROPVANGLOCATIES',
 'LISS',
 'NCOTOOL',
 'NIETVSLGTAB',
 'VEHTAB',
 'VRLGBAPERSOONKTAB',
 'VSLGTAB',
 'WOZ']

In [5]:
#Several IDs per dataset (19 datasets, including SPOLIS (next cell))
(
    df
    .filter(pl.col("Bestandsnaam").is_duplicated())
    .select(["Bestandsnaam"])
    .unique()
    .shape
)

(19, 1)

In [6]:
# 11 different IDs for SPOLIS
(
    df
    .filter(pl.col("Bestandsnaam") == "SPOLISBUS")
    .select("Bestandsnaam", "dataset_id", "valid_from", "valid_until")
    .sort(by="valid_from")
)

shape: (11, 4)
┌──────────────┬───────────────────────────────────────────┬────────────┬─────────────┐
│ Bestandsnaam ┆ dataset_id                                ┆ valid_from ┆ valid_until │
│ ---          ┆ ---                                       ┆ ---        ┆ ---         │
│ str          ┆ str                                       ┆ date       ┆ date        │
╞══════════════╪═══════════════════════════════════════════╪════════════╪═════════════╡
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E4108024847A ┆ 2010-01-01 ┆ 2015-01-01  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E410802AE699 ┆ 2015-01-01 ┆ 2016-01-01  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E410802EE816 ┆ 2016-01-01 ┆ 2016-11-22  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E41080337ACE ┆ 2016-11-22 ┆ 2018-03-22  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E410803922C0 ┆ 2018-03-22 ┆ 2020-02-12  │
│ …            ┆ …                                         ┆ …          ┆ …           │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E410805FD44A ┆ 2021-03-16 ┆ 2022-03-15  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E4108071EA4C ┆ 2022-03-15 ┆ 2023-02-17  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E41080767395 ┆ 2023-02-17 ┆ 2024-02-17  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E410807C72A7 ┆ 2024-02-17 ┆ 2025-01-01  │
│ SPOLISBUS    ┆ https://doi.org/10.57934/0B01E4108081B831 ┆ 2025-01-01 ┆ null        │
└──────────────┴───────────────────────────────────────────┴────────────┴─────────────┘

In [7]:
# Variables of SPOLIS per edition
df_spolis = (
    df
    .filter(pl.col("Bestandsnaam") == "SPOLISBUS")
    .sort(by="valid_from")
    .join(datasets_vars, on="dataset_id", how="left")
)

In [8]:
# Different number of variables
(
    df_spolis
    .group_by(["dataset_id","valid_from","valid_until"])
    .len("variable_name")
    .sort(by="valid_from")
)

shape: (11, 4)
┌───────────────────────────────────────────┬────────────┬─────────────┬───────────────┐
│ dataset_id                                ┆ valid_from ┆ valid_until ┆ variable_name │
│ ---                                       ┆ ---        ┆ ---         ┆ ---           │
│ str                                       ┆ date       ┆ date        ┆ u32           │
╞═══════════════════════════════════════════╪════════════╪═════════════╪═══════════════╡
│ https://doi.org/10.57934/0B01E4108024847A ┆ 2010-01-01 ┆ 2015-01-01  ┆ 184           │
│ https://doi.org/10.57934/0B01E410802AE699 ┆ 2015-01-01 ┆ 2016-01-01  ┆ 186           │
│ https://doi.org/10.57934/0B01E410802EE816 ┆ 2016-01-01 ┆ 2016-11-22  ┆ 200           │
│ https://doi.org/10.57934/0B01E41080337ACE ┆ 2016-11-22 ┆ 2018-03-22  ┆ 212           │
│ https://doi.org/10.57934/0B01E410803922C0 ┆ 2018-03-22 ┆ 2020-02-12  ┆ 220           │
│ …                                         ┆ …          ┆ …           ┆ …             │
│ https://doi.org/10.57934/0B01E410805FD44A ┆ 2021-03-16 ┆ 2022-03-15  ┆ 248           │
│ https://doi.org/10.57934/0B01E4108071EA4C ┆ 2022-03-15 ┆ 2023-02-17  ┆ 266           │
│ https://doi.org/10.57934/0B01E41080767395 ┆ 2023-02-17 ┆ 2024-02-17  ┆ 272           │
│ https://doi.org/10.57934/0B01E410807C72A7 ┆ 2024-02-17 ┆ 2025-01-01  ┆ 274           │
│ https://doi.org/10.57934/0B01E4108081B831 ┆ 2025-01-01 ┆ null        ┆ 274           │
└───────────────────────────────────────────┴────────────┴─────────────┴───────────────┘

In [9]:
# Comparing the last two (same number of variables)
df1 = df_spolis.filter(pl.col("dataset_id") == "https://doi.org/10.57934/0B01E410807C72A7").unique()
df2 = df_spolis.filter(pl.col("dataset_id") == "https://doi.org/10.57934/0B01E4108081B831").unique()

print("Present only in 1", set(df1["variable_name"]) - set(df2["variable_name"]))
print("Present only in 2", set(df2["variable_name"]) - set(df1["variable_name"]))

Present only in 1 set()
Present only in 2 set()

In [10]:
# Some variables have several IDs even within the same dataset
df1.filter(pl.col("variable_name")=="SIndAvrLkvAgWn")

shape: (2, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Bestandsn ┆ Bestandso ┆ Type      ┆ Status    ┆ … ┆ num_predi ┆ tijdstip_ ┆ valid_fro ┆ is_tijds │
│ aam       ┆ nderwerp  ┆ bestand   ┆ ---       ┆   ┆ cates     ┆ predicate ┆ m_right   ┆ tip      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ s         ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ ---       ┆ date      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆           ┆ list[str] ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SPOLISBUS ┆ SPOLIS    ┆ Catalogus ┆ Available ┆ … ┆ 14        ┆ []        ┆ 2018-02-0 ┆ false    │
│           ┆           ┆ bestand   ┆           ┆   ┆           ┆           ┆ 9         ┆          │
│ SPOLISBUS ┆ SPOLIS    ┆ Catalogus ┆ Available ┆ … ┆ 14        ┆ []        ┆ 2018-02-0 ┆ false    │
│           ┆           ┆ bestand   ┆           ┆   ┆           ┆           ┆ 9         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# See what's changed
df_combined = df1.join(df2, on="variable_name", suffix="_new")
vars_updated = []
for var in df1.columns:
    if var != "variable_name":
        df_f = df_combined.filter(pl.col(var) != pl.col(f"{var}_new"))
        if df_f.shape[0] > 0:
            print(var, df_f.shape[0])
            vars_updated.append(var)

dataset_id 548
valid_from 548
variable_id 548
description 52

In [12]:
# Basically no differences (some commas, quotes, etc)
var = "description"
df_combined.filter(pl.col(var) != pl.col(f"{var}_new")).select(["variable_name","description","description_new"])

shape: (52, 3)
┌───────────────────┬───────────────────────────────────────┬──────────────────────────────────────┐
│ variable_name     ┆ description                           ┆ description_new                      │
│ ---               ┆ ---                                   ┆ ---                                  │
│ str               ┆ str                                   ┆ str                                  │
╞═══════════════════╪═══════════════════════════════════════╪══════════════════════════════════════╡
│ CdCaoInl          ┆ Deze code mag alleen ingevuld worden  ┆ Deze code mag alleen ingevuld worden │
│                   ┆ bij payrollers.                       ┆ bij payrollers.                      │
│                   ┆                                       ┆                                      │
│                   ┆ Geef bij samenloop van meerdere       ┆ Geef bij samenloop van meerdere      │
│                   ┆ inleners in ee…                       ┆ inleners in ee…                      │
│ CdCaoInl          ┆ Deze code mag alleen ingevuld worden  ┆ Deze code mag alleen ingevuld worden │
│                   ┆ bij payrollers.                       ┆ bij payrollers.                      │
│                   ┆                                       ┆                                      │
│                   ┆ Geef bij samenloop van meerdere       ┆ Geef bij samenloop van meerdere      │
│                   ┆ inleners in ee…                       ┆ inleners in ee…                      │
│ SPRWAOAOF         ┆ Deze premie is onderdeel van de       ┆ Deze premie is onderdeel van de      │
│                   ┆ werknemersverzekeringen.              ┆ werknemersverzekeringen.             │
│                   ┆ Het loontijdvak is de periode tussen  ┆ Het loontijdvak is de periode tussen │
│                   ┆ SDATUM…                               ┆ SDATUM…                              │
│ SPRWAOAOF         ┆ Deze premie is onderdeel van de       ┆ Deze premie is onderdeel van de      │
│                   ┆ werknemersverzekeringen.              ┆ werknemersverzekeringen.             │
│                   ┆ Het loontijdvak is de periode tussen  ┆ Het loontijdvak is de periode tussen │
│                   ┆ SDATUM…                               ┆ SDATUM…                              │
│ SOPGRCHTVAKBSL    ┆ Het loontijdvak is de periode tussen  ┆ Het loontijdvak is de periode tussen │
│                   ┆ SDATUMAANVANGIKO en SDATUMEINDEIKO.   ┆ SDATUMAANVANGIKO en SDATUMEINDEIKO.  │
│                   ┆ Het opgebouwde recht op vak…          ┆ Het opgebouwde recht op vak…         │
│ …                 ┆ …                                     ┆ …                                    │
│ SCDAARD           ┆ Als de werknemer niet is verzekerd    ┆ Als de werknemer niet is verzekerd   │
│                   ┆ voor de werknemersverzekeringen       ┆ voor de werknemersverzekeringen      │
│                   ┆ (zoals meewerkende kinderen) geld…    ┆ (zoals meewerkende kinderen) geld…   │
│ SCAO              ┆ Dit is de code die het Ministerie van ┆ Dit is de code die het Ministerie    │
│                   ┆ Sociale Zaken en Werkgelegenheid of   ┆ van Sociale Zaken en Werkgelegenheid │
│                   ┆ het CBS heeft vastgesteld.…           ┆ of het CBS heeft vastgesteld.…       │
│ SCAO              ┆ Dit is de code die het Ministerie van ┆ Dit is de code die het Ministerie    │
│                   ┆ Sociale Zaken en Werkgelegenheid of   ┆ van Sociale Zaken en Werkgelegenheid │
│                   ┆ het CBS heeft vastgesteld.…           ┆ of het CBS heeft vastgesteld.…       │
│ SIndAvrLkvDgBafSb ┆ De inhoudingsplichtige/werkgever kan  ┆ De inhoudingsplichtige/werkgever kan │
│                   ┆ onder de volgende voorwaarden in      ┆ onder de volgende voorwaarden in     │
│                   ┆ aanmerking komen voor een loon…       ┆ aanmerking komen voor een loon…      │
│ SIndAvrLkvDgBafSb ┆ De inhoudingsplichtige/werkgever kan  ┆ De inhoudingsplichtige/werkgever kan │
│                   ┆ onder de volgende voorwaarden in      ┆ onder de volgende voorwaarden in     │
│                   ┆ aanmerking komen voor een loon…       ┆ aanmerking komen voor een loon…      │
└───────────────────┴───────────────────────────────────────┴──────────────────────────────────────┘